platform :ios, '16.0'
use_frameworks!
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end
